/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        // TestCases tests = new TestCases(); // Initialize your test class
        // Search_Amazon search = new Search_Amazon();
        // BookMyShow count = new BookMyShow();
        // LinkedIn profile = new LinkedIn();
        // NestedFrames frameObj = new NestedFrames();
        // WindowHandle windowHandleTest = new WindowHandle();
        IMDB_Ratings IMDBTest = new IMDB_Ratings();

        //TODO: call your test case functions one after other here

        // tests.testCase01();
        // search.searchAmazon();
        // count.openURL();
        // count.countHyperlinks();
        // count.imageURLs();
        // count.premiere();
        // profile.signIn("mailid@gmail.com", "password");
        // profile.signIn("mailid@gmail.com", "password");
        // profile.printCount();
        // profile.createPost("Test post. Automating create a post. 123456");
        // profile.postImage();
        // frameObj.openURL("https://the-internet.herokuapp.com/nested_frames");
        // frameObj.getBodyText();
        // windowHandleTest.openURL("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open");
        // windowHandleTest.windowHandle();
        IMDBTest.openURL("https://www.imdb.com/chart/top");
        IMDBTest.imdb_ratings();

        //END Tests

        // search.endTest();
        // count.endTest();
        // tests.endTest(); 
        // profile.endTest();
        // frameObj.endTest();
        // windowHandleTest.endTest();
        IMDBTest.endTest();
        // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
